# fly.toml app configuration file generated for ziji-bot-discord on 2025-09-02T14:52:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ziji-bot-discord'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 2003
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 4
  memory_mb = 2048
