const fs = require("node:fs");
const path = require("node:path");
const { useHooks } = require("zihooks");
const { Database, createModel } = require("@zibot/db");

const CLIENT_MODULES = {
	mongodb: "../node_modules/.prisma/client-mongo",
	sqlite: "../node_modules/.prisma/client-sqlite",
};

const DEFAULT_SQLITE_URL = "file:./jsons/ziDB.sqlite";
const DEFAULT_MONGO_DATABASE = "ziji";
const REDACTED_VALUE = "[REDACTED]";
const SENSITIVE_KEY_PATTERN = /(token|secret|password|cookie|authorization|auth)/i;

const MODEL_CONFIGS = {
	ZiUser: {
		delegate: "ziUser",
		fields: [
			"id",
			"userID",
			"username",
			"avatar",
			"name",
			"xp",
			"level",
			"coin",
			"lang",
			"volume",
			"color",
			"lastDaily",
			"dailyStreak",
			"lastHunt",
			"totalAnimals",
			"huntStats",
			"lootboxes",
			"fabledLootboxes",
			"cookiesGiven",
			"cookiesReceived",
			"lastCookie",
			"thankedCookies",
			"hoyoCookie",
			"genshinAutoClaim",
			"lastGenshinClaim",
			"petCare",
			"lastGive",
			"dailyGives",
			"dailyQuests",
			"weeklyQuests",
			"lastQuestReset",
			"lastWeeklyReset",
			"discordAccessToken",
			"userInfo",
			"guilds",
			"lastLogin",
			"loginCount",
			"createdAt",
			"lastBattle",
			"battleStats",
			"updatedAt",
			"afk",
			"afkReason",
			"afkTime",
			"promptHistory",
			"CurrentAI",
			"CurrentUser",
		],
		indexedFields: ["id", "userID"],
		jsonFields: ["huntStats", "thankedCookies", "petCare", "dailyQuests", "weeklyQuests", "userInfo", "guilds", "battleStats"],
		dateFields: [
			"createdAt",
			"lastDaily",
			"lastHunt",
			"lastCookie",
			"lastGenshinClaim",
			"lastGive",
			"lastQuestReset",
			"lastWeeklyReset",
			"lastLogin",
			"lastBattle",
			"updatedAt",
			"afkTime",
		],
		defaults: {
			level: 1,
			coin: 0,
			volume: 100,
			color: "Random",
			dailyStreak: 0,
			totalAnimals: 0,
			huntStats: {},
			lootboxes: 0,
			fabledLootboxes: 0,
			cookiesGiven: 0,
			cookiesReceived: 0,
			thankedCookies: [],
			genshinAutoClaim: false,
			dailyGives: 0,
			dailyQuests: [],
			weeklyQuests: [],
			userInfo: {},
			guilds: [],
			loginCount: 0,
			battleStats: { wins: 0, losses: 0, total: 0 },
			afk: false,
			afkReason: null,
			afkTime: null,
		},
		touchUpdatedAt: true,
	},
	ZiAutoresponder: {
		delegate: "ziAutoresponder",
		fields: ["id", "guildId", "trigger", "response", "options", "createdAt", "updatedAt"],
		indexedFields: ["id", "guildId"],
		jsonFields: ["options"],
		dateFields: ["createdAt", "updatedAt"],
		defaults: { options: { matchMode: "exactly" } },
	},
	ZiWelcome: {
		delegate: "ziWelcome",
		fields: ["id", "guildId", "channel", "content", "Bchannel", "Bcontent", "createdAt", "updatedAt"],
		indexedFields: ["id", "guildId"],
		jsonFields: [],
		dateFields: ["createdAt", "updatedAt"],
		defaults: {},
	},
	ZiGuild: {
		delegate: "ziGuild",
		fields: ["id", "guildId", "voice", "joinToCreate", "autoRole", "music_channel", "updatedAt", "noitu", "ticket", "youtube"],
		indexedFields: ["id", "guildId"],
		jsonFields: ["voice", "joinToCreate", "autoRole", "noitu", "ticket", "youtube"],
		dateFields: ["updatedAt"],
		defaults: {
			voice: { logMode: false },
			joinToCreate: {
				enabled: false,
				voiceChannelId: null,
				categoryId: null,
				defaultUserLimit: 0,
				tempChannels: [],
				blockedUser: [],
			},
			autoRole: { enabled: false, roleIds: [] },
			music_channel: null,
			noitu: { enabled: false, channel: null, lastPlayer: null, lastWord: null },
			ticket: { categoryId: null, staffRoleId: null, allowUserClose: true, logChannelId: null },
			youtube: { channels: [] },
		},
		touchUpdatedAt: true,
	},
	ZiConfess: {
		delegate: "ziConfess",
		fields: ["id", "enabled", "guildId", "channelId", "reviewSystem", "reviewChannelId", "currentId", "confessions"],
		indexedFields: ["id", "guildId"],
		jsonFields: ["confessions"],
		dateFields: [],
		defaults: { enabled: false, reviewSystem: false, reviewChannelId: null, currentId: 0, confessions: [] },
	},
	ZiNote: {
		delegate: "ziNote",
		fields: ["id", "guildId", "userId", "content", "createdAt", "updatedAt"],
		indexedFields: ["id", "guildId", "userId"],
		jsonFields: [],
		dateFields: ["createdAt", "updatedAt"],
		defaults: {},
	},
};

// NOTE: The remainder of this module is unchanged from the current implementation.
