function createGreetingAnimationPayload(type) {
	const isWelcome = type === "welcome";
	return {
		type: "animated",
		data: {
			title: "Welcome Card",
			format: "gif",
			duration: 1500,
			fps: 12,
			loop: 0,
			canvas: {
				title: "Welcome Card",
				width: 930,
				height: 280,
				background: "linear-gradient(135deg, #090614 0%, #1e1035 50%, #4a1d6e 100%)",
				elements: [
					{
						id: "avatar",
						type: "avatar",
						x: 860,
						y: 82,
						width: 140,
						height: 140,
						imageUrl: "{userAVTurl}",
						borderRadius: 999,
						border: "4px solid rgba(168, 85, 247, 0.6)",
					},
					{
						id: "title",
						type: "text",
						x: 213,
						y: -26,
						width: 650,
						height: 52,
						content: isWelcome ? "Welcome, {userName}!" : "Goodbye, {userName}!",
						color: "#ffffff",
						fontSize: 44,
						fontWeight: 700,
						textShadow: "0 0 10px #f43f5e, 0 0 24px #e11d48",
						shadowEnabled: false,
						shadowOffsetX: 2,
						shadowOffsetY: 3,
						shadowBlur: 6,
						shadowColor: "rgba(0, 0, 0, 0.9)",
						glowEnabled: true,
						glowBlur: 14,
						glowColor: "#f43f5e",
						glowIntensity: "medium",
					},
					{
						id: "subtitle",
						type: "text",
						x: 605,
						y: 122,
						width: 650,
						height: 38,
						content: isWelcome ? "Joined {guildName} - Ready for battle" : "Left {guildName} - Hope to see you again",
						color: "#c084fc",
						fontSize: 24,
						fontWeight: 500,
						textShadow: "2px 3px 6px rgba(0, 0, 0, 0.9), 0 0 16px #c084fc",
						shadowEnabled: true,
						shadowOffsetX: 2,
						shadowOffsetY: 3,
						shadowBlur: 6,
						shadowColor: "rgba(0, 0, 0, 0.9)",
						glowEnabled: true,
						glowColor: "#c084fc",
						glowBlur: 16,
						glowIntensity: "medium",
					},
					{
						id: "badge",
						type: "badge",
						x: 198,
						y: 264,
						width: 130,
						height: 32,
						content: isWelcome ? " NEW MEMBER" : " GOODBYE",
						color: "#ffffff",
						backgroundColor: "#7e22ce",
						borderRadius: 8,
						fontSize: 13,
						textShadow: "3px 4px 0px rgba(0, 0, 0, 0.95), 5px 8px 14px rgba(0, 0, 0, 0.7)",
						glowEnabled: false,
						glowColor: "#c084fc",
						glowBlur: 14,
						glowIntensity: "medium",
						shadowEnabled: true,
						shadowOffsetX: 3,
						shadowOffsetY: 4,
						shadowBlur: 14,
						shadowColor: "rgba(0, 0, 0, 0.95)",
					},
				],
				backgroundImageUrl:
					"https://twistedsifter.com/wp-content/uploads/2013/05/animated-gifs-of-fighting-game-backgrounds-25.gif",
			},
			tracks: [
				{
					elementId: "avatar",
					keyframes: [
						{
							time: 0,
							easing: "bounce",
							x: 20,
							y: 70,
							width: 110,
							height: 110,
							rotation: -12,
							scaleX: 0.8,
							scaleY: 0.8,
							opacity: 0,
							transform: {
								x: 20,
								y: 70,
								width: 110,
								height: 110,
								rotation: -12,
								scaleX: 0.8,
								scaleY: 0.8,
								anchorX: 0.5,
								anchorY: 0.5,
							},
						},
						{
							time: 450,
							easing: "ease-out",
							x: 36,
							y: 70,
							width: 140,
							height: 140,
							rotation: 6,
							scaleX: 1.05,
							scaleY: 1.05,
							opacity: 1,
							transform: {
								x: 36,
								y: 70,
								width: 140,
								height: 140,
								rotation: 6,
								scaleX: 1.05,
								scaleY: 1.05,
								anchorX: 0.5,
								anchorY: 0.5,
							},
						},
						{
							time: 800,
							x: 36,
							y: 70,
							width: 140,
							height: 140,
							rotation: 0,
							scaleX: 1,
							scaleY: 1,
							opacity: 1,
							transform: {
								x: 36,
								y: 70,
								width: 140,
								height: 140,
								rotation: 0,
								scaleX: 1,
								scaleY: 1,
								anchorX: 0.5,
								anchorY: 0.5,
							},
						},
						{
							time: 1296,
							x: 36,
							y: 70,
							width: 140,
							height: 140,
							rotation: 0,
							scaleX: 1,
							scaleY: 1,
							anchorX: 0.5,
							anchorY: 0.5,
							opacity: 1,
							transform: {
								x: 36,
								y: 70,
								width: 140,
								height: 140,
								rotation: 0,
								scaleX: 1,
								scaleY: 1,
								anchorX: 0.5,
								anchorY: 0.5,
							},
						},
						{
							time: 1500,
							x: 1034,
							y: 82,
							width: 140,
							height: 140,
							rotation: 180,
							scaleX: 1,
							scaleY: 1,
							anchorX: 0.5,
							anchorY: 0.5,
							opacity: 1,
							transform: {
								x: 1034,
								y: 82,
								width: 140,
								height: 140,
								rotation: 180,
								scaleX: 1,
								scaleY: 1,
								anchorX: 0.5,
								anchorY: 0.5,
							},
						},
					],
				},
				{
					elementId: "title",
					keyframes: [
						{
							time: 200,
							easing: "ease-out",
							x: 160,
							y: 55,
							width: 650,
							height: 52,
							rotation: -2,
							scaleX: 0.95,
							opacity: 0,
							transform: {
								x: 160,
								y: 55,
								width: 650,
								height: 52,
								rotation: -2,
								scaleX: 0.95,
							},
						},
						{
							time: 593,
							x: 205,
							y: 55,
							width: 650,
							height: 52,
							rotation: 0,
							scaleX: 1,
							opacity: 1,
							transform: {
								x: 205,
								y: 55,
								width: 650,
								height: 52,
								rotation: 0,
								scaleX: 1,
							},
						},
						{
							time: 1291,
							x: 205,
							y: 55,
							width: 650,
							height: 52,
							rotation: 0,
							scaleX: 1,
							scaleY: 1,
							anchorX: 0.5,
							anchorY: 0.5,
							opacity: 1,
							fontSize: 44,
							color: "#ffffff",
							glowColor: "#f43f5e",
							glowBlur: 14,
							textShadow: "0 0 10px #f43f5e, 0 0 24px #e11d48",
							transform: {
								x: 205,
								y: 55,
								width: 650,
								height: 52,
								rotation: 0,
								scaleX: 1,
								scaleY: 1,
								anchorX: 0.5,
								anchorY: 0.5,
							},
						},
						{
							time: 1461,
							x: 213,
							y: -51,
							width: 650,
							height: 52,
							rotation: 0,
							scaleX: 1,
							scaleY: 1,
							anchorX: 0.5,
							anchorY: 0.5,
							opacity: 1,
							fontSize: 44,
							color: "#ffffff",
							glowColor: "#f43f5e",
							glowBlur: 14,
							textShadow: "0 0 10px #f43f5e, 0 0 24px #e11d48",
							transform: {
								x: 213,
								y: -51,
								width: 650,
								height: 52,
								rotation: 0,
								scaleX: 1,
								scaleY: 1,
								anchorX: 0.5,
								anchorY: 0.5,
							},
						},
					],
				},
				{
					elementId: "subtitle",
					keyframes: [
						{
							time: 318,
							easing: "ease-out",
							x: 170,
							y: 115,
							width: 650,
							height: 38,
							opacity: 0,
							transform: {
								x: 170,
								y: 115,
								width: 650,
								height: 38,
							},
						},
						{
							time: 767,
							x: 205,
							y: 115,
							width: 650,
							height: 38,
							opacity: 1,
							transform: {
								x: 205,
								y: 115,
								width: 650,
								height: 38,
							},
						},
						{
							time: 1296,
							x: 205,
							y: 115,
							width: 650,
							height: 38,
							rotation: 0,
							scaleX: 1,
							scaleY: 1,
							anchorX: 0.5,
							anchorY: 0.5,
							opacity: 1,
							fontSize: 24,
							color: "#c084fc",
							glowColor: "#c084fc",
							glowBlur: 16,
							textShadow: "2px 3px 6px rgba(0, 0, 0, 0.9), 0 0 16px #c084fc",
							transform: {
								x: 205,
								y: 115,
								width: 650,
								height: 38,
								rotation: 0,
								scaleX: 1,
								scaleY: 1,
								anchorX: 0.5,
								anchorY: 0.5,
							},
						},
						{
							time: 1461,
							x: 1000,
							y: 122,
							width: 650,
							height: 38,
							rotation: 0,
							scaleX: 1,
							scaleY: 1,
							anchorX: 0.5,
							anchorY: 0.5,
							opacity: 1,
							fontSize: 24,
							color: "#c084fc",
							glowColor: "#c084fc",
							glowBlur: 16,
							textShadow: "2px 3px 6px rgba(0, 0, 0, 0.9), 0 0 16px #c084fc",
							transform: {
								x: 1000,
								y: 122,
								width: 650,
								height: 38,
								rotation: 0,
								scaleX: 1,
								scaleY: 1,
								anchorX: 0.5,
								anchorY: 0.5,
							},
						},
					],
				},
				{
					elementId: "badge",
					keyframes: [
						{
							time: 437,
							easing: "bounce",
							x: 205,
							y: 195,
							width: 130,
							height: 32,
							rotation: -6,
							scaleX: 0.85,
							opacity: 0,
							transform: {
								x: 205,
								y: 195,
								width: 130,
								height: 32,
								rotation: -6,
								scaleX: 0.85,
							},
						},
						{
							time: 859,
							x: 205,
							y: 175,
							width: 130,
							height: 32,
							rotation: 0,
							scaleX: 1,
							opacity: 1,
							transform: {
								x: 205,
								y: 175,
								width: 130,
								height: 32,
								rotation: 0,
								scaleX: 1,
							},
						},
						{
							time: 1293,
							x: 205,
							y: 175,
							width: 130,
							height: 32,
							rotation: 0,
							scaleX: 1,
							scaleY: 1,
							anchorX: 0.5,
							anchorY: 0.5,
							opacity: 1,
							fontSize: 13,
							color: "#ffffff",
							backgroundColor: "#7e22ce",
							glowColor: "#c084fc",
							glowBlur: 14,
							textShadow: "3px 4px 0px rgba(0, 0, 0, 0.95), 5px 8px 14px rgba(0, 0, 0, 0.7)",
							transform: {
								x: 205,
								y: 175,
								width: 130,
								height: 32,
								rotation: 0,
								scaleX: 1,
								scaleY: 1,
								anchorX: 0.5,
								anchorY: 0.5,
							},
						},
						{
							time: 1461,
							x: 198,
							y: 292,
							width: 130,
							height: 32,
							rotation: 0,
							scaleX: 1,
							scaleY: 1,
							anchorX: 0.5,
							anchorY: 0.5,
							opacity: 1,
							fontSize: 13,
							color: "#ffffff",
							backgroundColor: "#7e22ce",
							glowColor: "#c084fc",
							glowBlur: 14,
							textShadow: "3px 4px 0px rgba(0, 0, 0, 0.95), 5px 8px 14px rgba(0, 0, 0, 0.7)",
							transform: {
								x: 198,
								y: 292,
								width: 130,
								height: 32,
								rotation: 0,
								scaleX: 1,
								scaleY: 1,
								anchorX: 0.5,
								anchorY: 0.5,
							},
						},
					],
				},
			],
			templateVariables: {
				userAVTurl: "https://github.com/user-attachments/assets/ebbf178f-a0af-468c-bc6d-34f0502f30a8",
				userName: "ziji",
				guildName: "Hội Vô Danh 2",
			},
		},
	};
}

module.exports = {
	createGreetingAnimationPayload,
};
